name: CMake

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build CMake
      uses: ashutoshvarma/action-cmake-build@v1
      with:
        cxx: 23
        run-test: true
        install-build: true
      
